services:
  toturial-service:
    image: biandayu/jpademo:v1.0.3
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - SLEEP_LENGTH=5
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - example-mysql
      - collector

  example-mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14250:14250"
      - "16686:16686"

  collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver port
      - "8889:8889" # Promentheus exporter metrics
    depends_on:
      - jaeger-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prom-config.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - collector

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  db: