apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: biandayu/sample-spring-boot-jpa
    buildpacks:
      builder: "paketobuildpacks/builder:tiny"
deploy:
  kubectl:
    manifests:
      - k8s/secret.yaml
      - k8s/mysql-deployment.yaml
      - k8s/deployment.yaml