apiVersion: v1
kind: Service
metadata:
  name: example-mysql
  labels:
    app: example-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: example-mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: example-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mysql
  labels:
    app: example-mysql
spec:
  selector:
    matchLabels:
      app: example-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example-mysql
    spec:
      containers:
        - image: mysql:5.6
          name: example-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
